export const PATIENT_FIELDS = [
  {
    section: "Demographics",
    items: [
      { name: "Age", label: "Age", type: "number", min: 0 },
      {
        name: "Gender",
        label: "Gender",
        type: "select",
        options: [
          { value: 0, label: "Male" },
          { value: 1, label: "Female" },
        ],
      },
      {
        name: "Ethnicity",
        label: "Ethnicity",
        type: "number",
        helper: "Encoded categorical feature",
      },
      {
        name: "SocioeconomicStatus",
        label: "Socioeconomic Status",
        type: "number",
      },
      { name: "EducationLevel", label: "Education Level", type: "number" },
    ],
  },
  {
    section: "Lifestyle & Habits",
    items: [
      { name: "BMI", label: "BMI", type: "number", step: 0.1 },
      { name: "Smoking", label: "Smoking", type: "number" },
      { name: "AlcoholConsumption", label: "Alcohol Consumption", type: "number" },
      { name: "PhysicalActivity", label: "Physical Activity", type: "number" },
      { name: "DietQuality", label: "Diet Quality", type: "number" },
      { name: "SleepQuality", label: "Sleep Quality", type: "number" },
    ],
  },
  {
    section: "Family History",
    items: [
      {
        name: "FamilyHistoryKidneyDisease",
        label: "Kidney Disease",
        type: "number",
      },
      {
        name: "FamilyHistoryHypertension",
        label: "Hypertension",
        type: "number",
      },
      { name: "FamilyHistoryDiabetes", label: "Diabetes", type: "number" },
    ],
  },
  {
    section: "Medical History",
    items: [
      {
        name: "PreviousAcuteKidneyInjury",
        label: "Previous Acute Kidney Injury",
        type: "number",
      },
      {
        name: "UrinaryTractInfections",
        label: "Urinary Tract Infections",
        type: "number",
      },
      { name: "Edema", label: "Edema", type: "number" },
      { name: "FatigueLevels", label: "Fatigue Levels", type: "number" },
      { name: "NauseaVomiting", label: "Nausea / Vomiting", type: "number" },
      { name: "MuscleCramps", label: "Muscle Cramps", type: "number" },
      { name: "Itching", label: "Itching", type: "number" },
      {
        name: "QualityOfLifeScore",
        label: "Quality Of Life Score",
        type: "number",
      },
    ],
  },
  {
    section: "Vitals",
    items: [
      { name: "SystolicBP", label: "Systolic BP", type: "number" },
      { name: "DiastolicBP", label: "Diastolic BP", type: "number" },
    ],
  },
  {
    section: "Laboratory Values",
    items: [
      { name: "FastingBloodSugar", label: "Fasting Blood Sugar", type: "number" },
      { name: "HbA1c", label: "HbA1c", type: "number", step: 0.1 },
      { name: "SerumCreatinine", label: "Serum Creatinine", type: "number", step: 0.1 },
      { name: "BUNLevels", label: "BUN Levels", type: "number" },
      { name: "GFR", label: "GFR", type: "number" },
      { name: "ProteinInUrine", label: "Protein In Urine", type: "number" },
      { name: "ACR", label: "Albumin Creatinine Ratio (ACR)", type: "number" },
      {
        name: "SerumElectrolytesSodium",
        label: "Sodium",
        type: "number",
      },
      {
        name: "SerumElectrolytesPotassium",
        label: "Potassium",
        type: "number",
      },
      {
        name: "SerumElectrolytesCalcium",
        label: "Calcium",
        type: "number",
        step: 0.1,
      },
      {
        name: "SerumElectrolytesPhosphorus",
        label: "Phosphorus",
        type: "number",
        step: 0.1,
      },
      { name: "HemoglobinLevels", label: "Hemoglobin Levels", type: "number" },
      { name: "CholesterolTotal", label: "Cholesterol Total", type: "number" },
      { name: "CholesterolLDL", label: "Cholesterol LDL", type: "number" },
      { name: "CholesterolHDL", label: "Cholesterol HDL", type: "number" },
      {
        name: "CholesterolTriglycerides",
        label: "Cholesterol Triglycerides",
        type: "number",
      },
    ],
  },
  {
    section: "Medications",
    items: [
      { name: "ACEInhibitors", label: "ACE Inhibitors", type: "number" },
      { name: "Diuretics", label: "Diuretics", type: "number" },
      { name: "NSAIDsUse", label: "NSAIDs Use", type: "number" },
      { name: "Statins", label: "Statins", type: "number" },
      {
        name: "AntidiabeticMedications",
        label: "Antidiabetic Medications",
        type: "number",
      },
    ],
  },
  {
    section: "Environmental Factors",
    items: [
      {
        name: "HeavyMetalsExposure",
        label: "Heavy Metals Exposure",
        type: "number",
      },
      {
        name: "OccupationalExposureChemicals",
        label: "Occupational Chemical Exposure",
        type: "number",
      },
      { name: "WaterQuality", label: "Water Quality", type: "number" },
    ],
  },
  {
    section: "Healthcare Engagement",
    items: [
      {
        name: "MedicalCheckupsFrequency",
        label: "Medical Checkups Frequency",
        type: "number",
      },
      {
        name: "MedicationAdherence",
        label: "Medication Adherence",
        type: "number",
      },
      { name: "HealthLiteracy", label: "Health Literacy", type: "number" },
    ],
  },
];

export const SAMPLE_PATIENT = {
  Age: 68,
  Gender: 0,
  Ethnicity: 1,
  SocioeconomicStatus: 1,
  EducationLevel: 2,
  BMI: 29.8,
  Smoking: 1,
  AlcoholConsumption: 1,
  PhysicalActivity: 1,
  DietQuality: 1,
  SleepQuality: 2,
  FamilyHistoryKidneyDisease: 1,
  FamilyHistoryHypertension: 1,
  FamilyHistoryDiabetes: 1,
  PreviousAcuteKidneyInjury: 1,
  UrinaryTractInfections: 1,
  SystolicBP: 160,
  DiastolicBP: 95,
  FastingBloodSugar: 160,
  HbA1c: 8.5,
  SerumCreatinine: 3.8,
  BUNLevels: 55,
  GFR: 25,
  ProteinInUrine: 1,
  ACR: 450,
  SerumElectrolytesSodium: 134,
  SerumElectrolytesPotassium: 5.4,
  SerumElectrolytesCalcium: 8.2,
  SerumElectrolytesPhosphorus: 5.1,
  HemoglobinLevels: 10.5,
  CholesterolTotal: 240,
  CholesterolLDL: 160,
  CholesterolHDL: 35,
  CholesterolTriglycerides: 200,
  ACEInhibitors: 1,
  Diuretics: 1,
  NSAIDsUse: 1,
  Statins: 1,
  AntidiabeticMedications: 1,
  Edema: 1,
  FatigueLevels: 4,
  NauseaVomiting: 1,
  MuscleCramps: 1,
  Itching: 1,
  QualityOfLifeScore: 2,
  HeavyMetalsExposure: 1,
  OccupationalExposureChemicals: 1,
  WaterQuality: 0,
  MedicalCheckupsFrequency: 1,
  MedicationAdherence: 1,
  HealthLiteracy: 1,
};

